### ISSUE TITLE
Something wrong when set up the naturescape dataset

### ISSUE THREAD

**Issue by tdd233** [TOPO-EPFL/CrossLoc-Benchmark-Datasets#1]
Hi,

Thanks for the dataset, I'm very interested in your outstanding work!!!
However, when I set up the naturescape dataset following your instructions, the program produced the following error:
![image](https://user-images.githubusercontent.com/93235196/235122918-a4d29eb7-31d9-4e50-a74d-0b2ff1e4a254.png)
Looking forward to your reply.

**Comment by qiyan98** [comment]
Hi,

Thanks for your interest in our project! Could you please try to verify the raw dataset files first? You can do this by comparing the `md5sum` hash. We provided the original dataset `md5sum` at [here](https://onedrive.live.com/?authkey=%21AIAV5BIPjxUqrnQ&cid=6AE3F91331A91B79&id=6AE3F91331A91B79%2133408&parId=6AE3F91331A91B79%2133396&o=OneUp) and it's also shown below.

| Index | Filename                  | md5sum                           |
| ----- | ------------------------- | -------------------------------- |
| 1     | naturescape.tar.gz.partaa | cb6f3490c5e1319873f7684e16aba5c1 |
| 2     | naturescape.tar.gz.partab | 1b0dea64e10749be960d56fe8363340e |
| 3     | naturescape.tar.gz.partac | 807563b9c39ea7a0e3f2581bac2486f9 |
| 4     | naturescape.tar.gz.partad | 3bd03823ea812f73e025c2d4bb037149 |
| 5     | naturescape.tar.gz.partae | 2d189dab9adbbf964757f20842aac7f1 |
| 6     | naturescape.tar.gz.partaf | bd799c004ee79e228f1a6bfd0828e126 |
| 7     | naturescape.tar.gz.partag | 2e17d33fb4cfac81f03d05a08ad76bac |
| 8     | urbanscape.tar.gz.partaa  | 2829b96ca007ef4aeabde7806063fe57 |
| 9     | urbanscape.tar.gz.partab  | 8012b88485591819b738f88b733c3b3f |
| 10    | urbanscape.tar.gz.partac  | 796bbb6ab21d4eaf28436ef79a4009fb |
| 11    | urbanscape.tar.gz.partad  | 2dc1afa07f0b26edc7687477efe1fe90 |

**Comment by tdd233** [comment]
Thanks for your reply. I found that one raw file is not in accord with yours.
