### ISSUE TITLE
About Pose Matrix (extrinsic camera matrix) Caculation

### ISSUE THREAD

**Issue by VictorZoo** [TOPO-EPFL/CrossLoc-Benchmark-Datasets#2]
Hi,

I noticed that when converting rotation matrices, it is necessary to use the rotation in the END (East-North-Down) coordinate system in the ECEF (Earth-Centered, Earth-Fixed) coordinate system as a bridge for the conversion. I would like to ask, how should I perform the conversion if my current model is in the EPSG:32632 coordinate system? The reference links you provided are no longer accessible (https://www.fossen.biz/wiley/ed2/Ch2.pdf).

I would greatly appreciate it if you could reply to me.

Best regards
VictorZoo

**Comment by qiyan98** [comment]
Hi, thanks for your interest in our project. It's unfortunate that this reference link no longer works. You can still take a look at  https://apps.dtic.mil/dtic/tr/fulltext/u2/a484864.pdf, Section 4.3, 4.1 for related information.

I suppose you can follow the steps [here](https://github.com/TOPO-EPFL/CrossLoc-Benchmark-Datasets/blob/310ca9930e59164eecedd3e3575a4473e30a97b7/datasets/setup_dataset_utils.py#L52C28-L52C28) to get NED coordinates. In our workflow, we first obtain the geographic longitude/latitude/altitude values using `pyproj.Transformer.from_crs` then convert them to NED. If you can find a smilar way to convert the EPSG:32632 to standard ECEF coordinate in epsg:4978 or lon/lat/alt in epsg:4979, I believe you can reuse some part of our code.
