### ISSUE TITLE
About the Ground-truth Poses for UAV real images.

### ISSUE THREAD

**Issue by VictorZoo** [TOPO-EPFL/CrossLoc-Benchmark-Datasets#6]
Hi Yan Qi,

I noticed that in CrossLoc-Benchmark-Datasets, you provided "xxx_poses.npy", for example, "urbanscape-2020-11-11-planned_poses.npy", as poses file.

1. Is that the Ground-Truth (GT) poses for real images?
2. As I considered, GT poses is the RTK poses? Directly from the DJI Phantom 4? 
3. Why not using the photogrammetry results as GT? Cause I noticed that there are differences between real images and synthetic images.

Thank you very much.

Victor

**Comment by qiyan98** [comment]
Hi Victor,

Thanks for your questions.
1. The GT camera poses are contained in the `poses` folder, formatted as 4x4 cam-to-world transformation matrices stored in `txt` files. The `npy` files should contain the semantic labels.
2. Yes, GT poses are derived from a DJI Phantom 4 with RTK, but we conducted calibration (see below).
3. We conducted calibration using ground control points and photogrammetry tools and performed an error study (detailed in Appendix A.2) for the RTK poses. The conclusion is as follows:
>  Figure 7 shows the RTK geo-tag error statistics w.r.t. the computed photogrammetry ground truth. The geo-tag precision at the Urbanscape dataset is as small as 4 cm, while it degrades significantly in the Naturescape dataset. One can observe that there is a mean positional error bias. In the next steps, this bias was subtracted for all images of each drone, bringing the error to a lower level (mean error = 0.42 m).

In both naturescape and urbanscape datasets, the drone was flying in the air and quite far from the visual objects (e.g., houses). The slight uncertainty in poses is not a serious bottleneck in our tasks.

Moreover, the mismatch between synthetic and real images can be attributed to the quality of the geo-data used for rendering. For example, the satellite data and 3D point cloud are provided as-is. They don't have centimeter-level accuracy, and they are static and don't reflect dynamic scene changes (e.g., construction sites or light change). These factors can lead to more drastic mismatch (e.g., we list a few failure cases in Figure 8).

**Comment by VictorZoo** [comment]
Thank you for the responce.

Our current experiment requires more accurate poses. If it is convenient, could you provide the computed photogrammetry ground truth?

**Comment by qiyan98** [comment]
Hi Victor,

Unfortunately, I don't have access to the photogrammetry ground-truth as of now. The data was stored in one of my previous institutions.

**Comment by VictorZoo** [comment]
oh，whats a pity！ T.T

**Comment by VictorZoo** [comment]
Thank you very much for your reply. If can get the calculated pose, I will be very grateful.
